ADD public/app /app/public/
FROM actionloop/standalone:config
#ADD public /app/public/
ADD public/app /app/public/
ADD actions/manifest.yaml /app/actions/manifest.yaml
ADD actions/deploy  /app/actions/deploy
