name: Test Build
on: [push]
jobs:

  build:
    name: Test Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.12', '1.13']
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        #if [ -f Gopkg.toml ]; then
        #    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        #    dep ensure
        #fi

    - name: Build
      run: |
        apt-get install libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
        env GO111MODULE=on go build -o bin/iosdk

    # - name: Go test
    # run: cd wskide && go test -v

    - name: Test iosdk
      run : |
        docker pull openwhisk/standalone:nightly
        docker pull actionloop/ide-js:latest
        docker pull library/redis:5
        echo "1" | bin/iosdk config
        bin/iosdk start "" --skip-docker-version
        docker exec -t ide-js sh /home/project/test.sh
