name: Test Build
on: [push]
jobs:

  build:
    name: Test Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #go: ['1.12', '1.13']
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        go: ['1.13']
        os: [ubuntu-latest]
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
        sudo apt install nodejs
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        nvm install v10

    - name: Build
      run: |
        export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        nvm use v10
        docker login -u iosdk -p 79be109a-101a-47cc-8d28-2adeb1d60a6e
        make
