name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.13']
        os: [ubuntu-latest]
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        source $HOME/.nvm/nvm.sh
        nvm install v10

    # uncomment this if you need to debug
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v2

    - name: Build
      run: |
        source $HOME/.nvm/nvm.sh
        nvm use v10
        docker login -u iosdk -p 79be109a-101a-47cc-8d28-2adeb1d60a6e
        make
